name: firestore_cache
description: A new Flutter package project.
version: 0.1.0
author: zeshuaro
homepage: https://github.com/zeshuaro/firestore_cache

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.0+1
  shared_preferences: ^0.5.7
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore_mocks: ^0.4.3+1
